"""Portas (interfaces) que o domínio usa. Adaptadores concretos ficam em energia.adapters."""

from __future__ import annotations

from datetime import date, datetime
from typing import Protocol

from .domain.models import (
    Alert,
    DemandWindow,
    MeterConfig,
    MeterKey,
    MeterState,
    MonthRollup,
    SiteConfig,
    TenantConfig,
)


class StateRepository(Protocol):
    # cadastro
    def get_tenant(self, tenant_id: str) -> TenantConfig | None: ...
    def put_tenant(self, tenant: TenantConfig) -> None: ...
    def put_site(self, site: SiteConfig) -> None: ...
    def list_sites(self, tenant_id: str) -> list[SiteConfig]: ...
    def get_meter(self, key: MeterKey) -> MeterConfig | None: ...
    def put_meter(self, meter: MeterConfig) -> None: ...
    def list_meters(self, tenant_id: str) -> list[MeterConfig]: ...

    # operação
    def get_state(self, key: MeterKey) -> MeterState | None: ...
    def list_states_ingested_before(self, cutoff: datetime) -> list[MeterState]: ...
    def save_state(self, state: MeterState, expected_version: int) -> bool:
        """Grava se a versão armazenada for a esperada (escrita condicional). Devolve False em conflito."""
        ...

    def commit_processing(
        self,
        state: MeterState,
        expected_version: int,
        windows: list[DemandWindow],
        rollups: list[MonthRollup],
        alerts: list[Alert],
    ) -> bool:
        """Persiste toda a mudança de um processamento atomicamente, se a versão ainda for a esperada."""
        ...

    def save_window(self, window: DemandWindow) -> None: ...
    def list_windows(self, key: MeterKey, day: date) -> list[DemandWindow]: ...
    def get_month(self, key: MeterKey, month: str) -> MonthRollup | None: ...
    def save_month(self, rollup: MonthRollup) -> None: ...
    def save_alert(self, alert: Alert) -> None: ...
    def list_alerts(self, tenant_id: str, limit: int = 50) -> list[Alert]: ...


class EventSink(Protocol):
    def emit(self, detail_type: str, detail: dict) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
